language: rust

os:
  - linux
  - mac
  - windows

rust: nightly

env: TARGET=thumbv7em-none-eabihf

matrix:
  allow_failures:
    - os: windows # see https://travis-ci.community/t/rust-error-could-not-compile-winapi/268

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

# cache: cargo

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - staging
    - trying
    - master

notifications:
  email:
    on_success: never
